### ISSUE TITLE
Preservation of /etc/ignition files not contained in recommended volume

### ISSUE THREAD

**Issue by thirdgen88** [thirdgen88/ignition-docker#1]
The README.md suggests that preservation of the Ignition Gateway "instance data" can be done with a named volume against `/var/lib/ignition/data`.  In the current `Dockerfile`, there are several files linked from there back to `/etc/ignition`, namely:

* ignition.conf
* gateway.xml
* log4j.properties

Should probably have these directly placed in `/var/lib/ignition/data` by the install process instead of linked as a convenience measure for volume-mapping.

**Comment by thirdgen88** [comment]
Fixed with update to bring those configuration files directly into `/var/lib/ignition/data`

**Comment by M0rfic** [comment]
Hi Kevin,

Quick question, how/when can one use the `/var/lib/ignition` (as specified on the docker hub page)  volume bind to persist data? For example trying `docker run --name ignition -v /opt/ignition:/var/lib/ignition/data -d kcollins/ignition` on a fresh machine, results in:

```
morfic@blackhole:~$ sudo docker logs ignition
FATAL  | wrapper  | Unable to open configuration file: /var/lib/ignition/data/ignition.conf (No such file or directory)
FATAL  | wrapper  |   Current working directory: /usr/local/share/ignition
FATAL  | wrapper  |   The Wrapper will stop.
```

Kind regards

**Comment by thirdgen88** [comment]
@M0rfic, I see the same behavior here..  I'm certain that this worked at some point so I'll need to see what happened..  Many of the times I use this image I'm using it in a docker-compose setup, e.g.:

```yaml
version: '3'
services:
  gateway:
    image: "kcollins/ignition:latest"
    volumes:
      - gateway_data:/var/lib/ignition
    ports:
      - "8088:8088"
  db:
    image: "mysql:5.7"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ignition

volumes:
  gateway_data:
  db_data:

```

Just put the above into a `docker-compose.yml` inside of an empty directory, `cd` to it and run `docker-compose up -d`.  You can then shutdown and remove the containers (preserving the volumes) with `docker-compose down` (you can wipe everything with `docker-compose down -v`).

I just tested this and it successfully preserves things as expected.  I'll get back with you as to why the base bind-mounting isn't behaving properly.
