### ISSUE TITLE
docker-entrypoint.sh fails when using a bind mount volume

### ISSUE THREAD

**Issue by kgamble96** [thirdgen88/ignition-docker#25]
I  have tested this out in a few different images but whenever you try to run a container with a host bind mount the `docker-entrypoint.sh` fails to complete.

If you run the following container:
`docker run -P -e GATEWAY_ADMIN_PASSWORD=password -v /home/username/ignition_data:/var/lib/ignition kcollins/ignition:latest`

Than it will start, create the folder, and then fail on line 447 of the entrypoint script with the following error:
`/usr/local/bin/docker-entrypoint.sh: line 447: /usr/local/share/ignition/data/.docker-init-complete: No such file or directory`

The purpose of even doing this, is that starting in 8.0.13 with Perspective theming, there is a pretty constant need to open the theme files and edit them from your host, as they are stored in the `/data/modules/com.inductiveautomation.perspective/themes` so instead of having to enter the cli for the container, it would be much easier to be able to access them directly from your host.

**Comment by thirdgen88** [comment]
@kgamble96, try the following, where the `device` path is an **empty** folder on your host:
```
docker volume create -d local -o type=none \
  -o o=bind \
  -o device=/home/username/ignition_data gw-data
```

... then, start the container against that bind-mount volume (make sure you target `/var/lib/ignition/data`, **not** `/var/lib/ignition`, otherwise you'll run into trouble updating your gateway version later):
```
docker run -P -e GATEWAY_ADMIN_PASSWORD=password \
  -v gw-data:/var/lib/ignition/data kcollins/ignition:latest
```

The above solution has the effect of populating that empty-folder bind-mount with the initial contents from the container (which is _not_ the behavior with the simpler bind-mount syntax directly in `docker run`).  From there, you should then be able to edit files there directly and see their effect in the gateway.  Let me know if this gets you going!

**Comment by kgamble96** [comment]
I recieved the following error
![image](https://user-images.githubusercontent.com/51039224/84574014-f3b73000-ad71-11ea-85ec-2e28f52370c9.png)

**Comment by kgamble96** [comment]
Weird, I tried cleaning up a few things and then eventually did it again, and now it worked? 
Either way thank you!

My next question I guess then, is it possible to set device mounts like this through `docker-compose`?

**Comment by kgamble96** [comment]
Actually figured it out incase anyone else is curious and ends up here trying to figure it out
```
version: "3.8"
services:
  ignition:
    image: kcollins/ignition:latest  # You can change `latest` to a specific version, e.g. `8.0.5`
    ports:
      - "8088:8088"
    volumes:
      # - './Backup.gwbk:/restore.gwbk'
      - ignition_data:/var/lib/ignition/data
    environment:
      GATEWAY_ADMIN_PASSWORD: password

volumes:
  ignition_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/ignition_data
      o: bind
```
