### ISSUE TITLE
Comissioning Failure when persistent volume mounted

### ISSUE THREAD

**Issue by eskemojoe007** [thirdgen88/ignition-docker#39]
The following `docker-compose` works great for me:
```yml
  ignition:
    image:           kcollins/ignition:latest
    container_name:  ignition
    restart:         unless-stopped
    ports:
      - "2088:8088"
    # volumes:
    #   - ./ignitiondata:/var/lib/ignition/data
    environment:
      - GATEWAY_ADMIN_PASSWORD=password
      - IGNITION_EDITION=full
      # - IGNITION_STARTUP_DELAY=120
      # - IGNITION_COMMISSIONING_DELAY=60
```

When I uncomment the volumes:

```yml
  ignition:
    image:           kcollins/ignition:latest
    container_name:  ignition
    restart:         unless-stopped
    ports:
      - "2088:8088"
    volumes:
      - ./ignitiondata:/var/lib/ignition/data
    environment:
      - GATEWAY_ADMIN_PASSWORD=password
      - IGNITION_EDITION=full
      # - IGNITION_STARTUP_DELAY=120
      # - IGNITION_COMMISSIONING_DELAY=60
```

I get the following logs on repeat:
```bash
Provisioning will be logged here: /usr/local/share/ignition/logs/provisioning.log

Waiting for commissioning servlet to become active...

Failed to detect RUNNING status during Commissioning Phase after 30 delay.
```

**Comment by thirdgen88** [comment]
In order to use bind mounts under Docker Engine, you cannot use the "short syntax", as this does not pre-populate the target volume location with the pre-existing contents from the image on first launch.  See the guidance in my comment on #36 for more detail (which also references #25).  

Note: If you're using bind mounts and you're running on Linux (Docker Desktop handles some of this on the Mac/Windows side), you have to be very conscious about permissions as well to ensure that [the default] UID/GID 999 has write permission to your folder.

I'm working on some updates that will show up soon for a new empty-volume-mount option for bind mounts that will enable better compatibility with other container engines that expect those bind mount target paths to be able to be empty.  More on that soon...

**Comment by eskemojoe007** [comment]
I got it working with #25.  I've never had to specify a volume like that (and I have over 20+ volumes running).  I'm curious as to why that's necessary here.

For future reference my docker compose looks like:
```yml
services:
  ignition:
    image:           kcollins/ignition:latest
    container_name:  ignition
    restart:         unless-stopped
    ports:
      - "2088:8088"
    volumes:
      - ignition_data:/var/lib/ignition/data
    environment:
      - GATEWAY_ADMIN_PASSWORD=password
      - IGNITION_EDITION=full
volumes:
  ignition_data:
    driver: local
    driver_opts:
      type: none
      device: ./ignition_data
      o: bind
```
