### ISSUE TITLE
Issues with creating a new MAKER container with the nightly(from yesterday) 

### ISSUE THREAD

**Issue by tord-v** [thirdgen88/ignition-docker#41]
Im trying to create a container based on the nightly build.

I use my old compose file from 8.0.16 which provides a licence key and activation_token. 

Every time I open the webserver I get promted about username/password/licence. Which is allready provided by the compose file.

The error logs from 'docker logs [container]':
![image](https://user-images.githubusercontent.com/57943426/98585327-61d33500-22c7-11eb-88a9-cc5092e84c4f.png)
or this one if i reboot container:
![image](https://user-images.githubusercontent.com/57943426/98585636-df974080-22c7-11eb-9479-ca76cbee7596.png)

docker-compose file:
```
version: '2.2'
services:
  gateway:
    image: kcollins/ignition:nightly
    ports:
      - "8088:8088"
    stop_grace_period: 30s
    restart: always
    volumes:
      - /home/pi/dockerVolumes/IgnitionData/ignition.conf:/var/lib/ignition/data/ignition.conf
      - my-ignition-data:/var/lib/ignition/data
      - /home/pi/dockerVolumes/IgnitionModules:/modules
      - /home/pi/dockerVolumes/IgnitionActivationToken/activation-token:/activation-token
      - /home/pi/dockerVolumes/IgnitionBackup/IgnitionHome_Ignition-backup.gwbk:/restore.gwbk
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      GATEWAY_MODULES_ENABLED: perspective,opc-ua,tag-historian,alarm-notification,sfc
      GATEWAY_SYSTEM_NAME: "XXXXXX"
      GATEWAY_ADMIN_PASSWORD: "password"
      IGNITION_EDITION: "maker"
      GATEWAY_INIT_MEMORY: "1024"
      GATEWAY_MAX_MEMORY: "2048"
      TZ: "Europe/Oslo"
      IGNITION_LICENSE_KEY: "XXXX-XXXX"
      IGNITION_ACTIVATION_TOKEN_FILE: "/activation-token"
      IGNITION_COMMISSIONING_DELAY: "60"
      IGNITION_STARTUP_DELAY: "300"

volumes:
  my-ignition-data:
```
