### ISSUE TITLE
Permission Denied Error on Persistent Storage

### ISSUE THREAD

**Issue by williamsrAndrew** [thirdgen88/ignition-docker#55]
Version: 8.1.4
Setup: Kubernetes k8s with Rancher 2.5.7 Frontend
Problem:
This might be a relatively niche setup, and I'm not sure if this applies to other Kubernetes setups, but I've spun up many different services and never had this type of problem, so it might be something to look at for future releases.
I tried running Ignition Maker edition and kept getting crash loop back-off trying to bind mount a directory from the node (I tried /var/lib/ignition/data and /data), the error I received was:

`/usr/local/bin/docker-entrypoint.sh: line 286: /var/lib/ignition/data/.docker-init-complete: Permission denied`

Looking through the issues here I found that I should create a persistent volume, but this gave the same error. I tried both HostPath volumes and Local volumes but didn't have any luck. I got a hint from another issue discussing permissions, so I tried changing the permissions on my local $PWD/ignition_data directory:

`sudo chmod 777 ignition_data`

After this, I tried mounting the volume at /var/lib/ignition/data and this time the Pod actually started, but it still kept crashing with this log output:

```
init     | Added Init Setting SystemName=Ignition-Maker
init     | Processing Module Enable/Disable...
  Disabling 'Web Browser Module.modl'
  Disabling 'SMS Notification-module.modl'
  Disabling 'BACnet Driver-module.modl'
  Disabling 'Serial Support Client-module.modl'
  Disabling 'Voice Notification-module.modl'
  Disabling 'Vision-module.modl'
  Disabling 'DNP3-Driver.modl'
  Disabling 'Enterprise Administration-module.modl'
  Disabling 'Symbol Factory-module.modl'
init     | Starting Ignition Gateway...
init     | Initiating commissioning helper functions...
FATAL  | wrapper  | Unable to open configuration file: data/ignition.conf (No such file or directory)
FATAL  | wrapper  |   Current working directory: /usr/local/share/ignition
FATAL  | wrapper  |   The Wrapper will stop.
```

So then I tried mounting to /data, and using a Persistent Volume with HostPath as the source, I finally got this running! 

Here is a bit of the deployment configuration that Rancher creates. I removed a lot of the fluff and just tried to leave the important stuff. Again, I needed to chmod the ignition_data folder in order to get running. 
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ignition-maker
spec:
  template:
    spec:
      containers:
      - env:
        - name: GATEWAY_SYSTEM_NAME
          value: Ignition-Maker
        - name: IGNITION_EDITION
          value: MAKER
        - name: GATEWAY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: GATEWAY_ADMIN_PASSWORD
              name: ignition-secrets
              optional: false
        - name: IGNITION_ACTIVATION_TOKEN
          valueFrom:
            secretKeyRef:
              key: IGNITION_ACTIVATION_TOKEN
              name: ignition-secrets
              optional: false
        - name: IGNITION_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: IGNITION_LICENSE_KEY
              name: ignition-secrets
              optional: false
        image: kcollins/ignition:8.1.4
        imagePullPolicy: Always
        name: ignition-maker
        ports:
        - containerPort: 8088
          hostPort: 8088
          name: webgui
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: ignition-data
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ignition-data
        persistentVolumeClaim:
          claimName: ignition-data
```
