### ISSUE TITLE
Linking Sepasoft modules

### ISSUE THREAD

**Issue by dubeg** [thirdgen88/ignition-docker#79]
I get a certificate error (?) when trying to link up Sepasoft's modules (tried with 3.81.1 SP6, 7, 8 & 3.81.3 RC1) .
```
gateway_1  | init     | Existing Volume detected at /data, relinking data volume locations prior to Gateway Launch...
gateway_1  | init     | Searching for third-party modules...
gateway_1  | init     | Linking Module: OEE_Downtime-module.modl
gateway_1  |
gateway_1  | Warning:
gateway_1  | The certificate #3 of 3 uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
gateway_1 exited with code 1
```
I have the following compose file:
```
version: '3.1'
services:
  gateway:
    image: kcollins/ignition:latest
    ports:
      - "8091:8088"
    stop_grace_period: 30s
    volumes:
      - ./data:/data
      - ./modules:/modules
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      GATEWAY_SYSTEM_NAME: "Ignition-Sample"
      IGNITION_EDITION: FULL
      GATEWAY_ADMIN_USERNAME: admin
      GATEWAY_ADMIN_PASSWORD: admin
```
My modules folder contains:
- OEE_Downtime-module.modl
- Trace-module.modl
- Production-module.modl

It used to work on Ignition 8.1.9, I guess the `SHA1withRSA` issue came with Ignition 8.1.10. I'm not sure this is a problem with Ignition since the certificate is probably for Sepasoft modules. Should I create a ticket on their support website, or can you guys tell them?
